FROM maven:3.8.6-openjdk-11
WORKDIR /test
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN mvn -f test/boxfuse-sample-java-war-hello/pom.xml package
VOLUME /maven
RUN cp /test/boxfuse-sample-java-war-hello/target/hello-1.0.war /maven